//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoas
    {
        public int PessoasID { get; set; }
        public string PrimeiroNome { get; set; }
        public string UltimoNome { get; set; }
        public string Cidade { get; set; }
        public string Endereco { get; set; }
    }
}
